name: ChatSound
description: Play a sound when you chat. You can change Volume, Picth and Sound.
author: CIVN
website: http://civn.xyz/
main: org.civn.chatsound.ChatSound
version: 1.1

commands:
  chatsound:
    description: ChatSound!
    aliases: cs
    usage: /chatsound
    permission: chatsound.cs
    permission-message: You don't have <permission>